{
  "openapi": "3.0.4",
  "info": {
    "title": "Reds App API: Swagger Documentation - OpenAPI 3.0",
    "description": "This is a documentation page for the Reds App server-side API created by IFB398/IFB399 Team 125 based on the OpenAPI 3.0 specification.\n\nLinks:\n- [GitHub Repository](https://github.com/VmiteOCE/IFB398-T125)",
    "termsOfService": "https://swagger.io/terms/",
    "contact": {
      "email": "apiteam@swagger.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "1.0.27"
  },
  "externalDocs": {
    "description": "Find out more about Swagger",
    "url": "https://swagger.io"
  },
  "servers": [
    {
      "url": "https://localhost:3000/",
      "description": "Local Development Server"
    }
  ],
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "tags": [
    {
      "name": "games",
      "description": "Create, delete, or modify a game"
    },
    {
      "name": "events",
      "description": "Create, delete, or modify a game event"
    },
    {
      "name": "user",
      "description": "User authentication and management"
    }
  ],
  "paths": {
    "/games": {
      "post": {
        "tags": [
          "games"
        ],
        "summary": "Create a new game",
        "description": "Creates a new game in the database with an auto-incrementing ID value. Accepts JSON or URL-encoded form data.",
        "operationId": "createGame",
        "requestBody": {
          "$ref": "#/components/requestBodies/GameInputRequestBody"
        },
        "responses": {
          "201": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GameCreateResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "get": {
        "tags": [
          "games"
        ],
        "summary": "Get all game details",
        "description": "Retrieves a list of all games stored in the database.",
        "operationId": "getAllGames",
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetAllGamesResponse"
                }
              }
            }
          },
          "404": {
            "description": "No games in database",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NoGamesErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/games/{game_id}": {
      "get": {
        "tags": [
          "games"
        ],
        "summary": "Get details of an existing game",
        "description": "Gets the details of a game with the entered game_id.",
        "operationId": "getGameDetails",
        "parameters": [
          {
            "name": "game_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the game to get details of",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetSingleGameResponse"
                }
              }
            }
          },
          "404": {
            "description": "Game not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingGameErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "put": {
        "tags": [
          "games"
        ],
        "summary": "Update details of an existing game",
        "description": "Updates the details of a game with the entered game_id. Accepts JSON or URL-encoded form data.",
        "operationId": "updateGame",
        "parameters": [
          {
            "name": "game_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the game to update",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/GameInputRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GameUpdateResponse"
                }
              }
            }
          },
          "404": {
            "description": "Game not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingGameErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "delete": {
        "tags": [
          "games"
        ],
        "summary": "Delete an existing game",
        "description": "Deletes a game with the entered game_id. Additionally deletes all events associated with the entered game.",
        "operationId": "deleteGame",
        "parameters": [
          {
            "name": "game_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the game to delete",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GameDeleteResponse"
                }
              }
            }
          },
          "404": {
            "description": "Game not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingGameErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/events": {
      "post": {
        "tags": [
          "events"
        ],
        "summary": "Log a game event",
        "description": "Creates a new game event in the database with an auto-incrementing ID value. Accepts JSON or URL-encoded form data.",
        "operationId": "createEvent",
        "requestBody": {
          "$ref": "#/components/requestBodies/EventInputRequestBody"
        },
        "responses": {
          "201": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EventCreateResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/events/game/{game_id}": {
      "get": {
        "tags": [
          "events"
        ],
        "summary": "Get all game events for a specific game_id",
        "description": "Gets the details of a game with the entered game_id.",
        "operationId": "getGameEvents",
        "parameters": [
          {
            "name": "game_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the game to get details of",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetGameEventsResponse"
                }
              }
            }
          },
          "404": {
            "description": "Game not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingGameErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/events/{event_id}": {
      "get": {
        "tags": [
          "events"
        ],
        "summary": "Get details of an existing game event",
        "description": "Gets the details of a game event with the entered event_id.",
        "operationId": "getEvent",
        "parameters": [
          {
            "name": "event_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the game event to get details of",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetEventResponse"
                }
              }
            }
          },
          "404": {
            "description": "Event not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingEventErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "put": {
        "tags": [
          "events"
        ],
        "summary": "Update an existing game event",
        "description": "Updates the details of a game game event with the entered event_id. Accepts JSON or URL-encoded form data",
        "operationId": "updateEvent",
        "parameters": [
          {
            "name": "event_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the event to update",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "requestBody": {
          "$ref": "#/components/requestBodies/EventInputRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EventUpdateResponse"
                }
              }
            }
          },
          "404": {
            "description": "Event not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingEventErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "delete": {
        "tags": [
          "events"
        ],
        "summary": "Delete an existing game event",
        "description": "Deletes a game event with the entered event_id",
        "operationId": "deleteEvent",
        "parameters": [
          {
            "name": "event_id",
            "in": "path",
            "required": true,
            "description": "The unique ID of the game event to delete",
            "schema": {
              "type": "integer",
              "example": 1
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GameDeleteResponse"
                }
              }
            }
          },
          "404": {
            "description": "Event not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MissingEventErrorResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/user": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Create a new user.",
        "description": "This can only be done by a logged in admin user.",
        "operationId": "createUser",
        "requestBody": {
          "$ref": "#/components/requestBodies/UserCreateRequestBody"
        },
        "responses": {
          "201": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserCreateResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Get a list of all users.",
        "description": "This can only be done by a logged in admin user.",
        "operationId": "getUsers",
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetUsersResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "patch": {
        "tags": [
          "user"
        ],
        "summary": "Update password or role of an existing user.",
        "description": "This can only be done by a logged in admin user. Intended for use on a user management page.",
        "operationId": "updateUser",
        "requestBody": {
          "$ref": "#/components/requestBodies/UserUpdateRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserUpdateResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Delete an existing user.",
        "description": "This can only be done by a logged in admin user.",
        "operationId": "deleteUser",
        "requestBody": {
          "$ref": "#/components/requestBodies/UserDeleteRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserDeleteResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/user/login": {
      "post": {
        "tags": [
          "user"
        ],
        "summary": "Logs user into the system.",
        "description": "Log an existing user into the system.",
        "operationId": "loginUser",
        "requestBody": {
          "$ref": "#/components/requestBodies/UserLoginRequestBody"
        },
        "responses": {
          "201": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserLoginResponse"
                }
              }
            }
          },
          "500": {
            "description": "Login error"
          }
        },
        "security": []
      }
    },
    "/user/password": {
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Update password for the logged in user.",
        "description": "Only available to logged in users.",
        "operationId": "updatePassword",
        "requestBody": {
          "$ref": "#/components/requestBodies/UpdatePasswordRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdatePasswordResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/user/keybinds": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Retrieves keybindings for the logged in user.",
        "description": "Returns a JSON object containing a full keymap if the user has modified any keybindings. If no keybinds have been altered, keybinds returns as null.",
        "operationId": "getKeybinds",
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetKeybindsResponse"
                },
                "examples": {
                  "keybindsFound": {
                    "$ref": "#/components/schemas/Keybinds"
                  },
                  "noKeybinds": {
                    "value": {
                      "error": false,
                      "keybinds": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Updates keybindings for the logged in user.",
        "description": "Takes a full keymap and saves the cusom keybinds for the logged in user.",
        "operationId": "updateKeybinds",
        "requestBody": {
          "$ref": "#/components/requestBodies/UpdateKeybindsRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateKeybindsResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Resets keybindings for the logged in user to default.",
        "description": "Resets any existing keybinds, reverting the user to default settings.",
        "operationId": "resetKeybinds",
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResetKeybindsResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    },
    "/user/settings": {
      "get": {
        "tags": [
          "user"
        ],
        "summary": "Retrieves settings for the logged in user.",
        "description": "Returns a JSON object containing a full settings map if the user has modified any settings. If no settings have been altered, settings returns as null.",
        "operationId": "getSettings",
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/GetSettingsResponse"
                },
                "examples": {
                  "settingsFound": {
                    "$ref": "#/components/schemas/Settings"
                  },
                  "noSettings": {
                    "value": {
                      "error": false,
                      "keybinds": null
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "put": {
        "tags": [
          "user"
        ],
        "summary": "Updates settings for the logged in user.",
        "description": "Takes a full settings map and saves the cusom settings for the logged in user.",
        "operationId": "updateSettings",
        "requestBody": {
          "$ref": "#/components/requestBodies/UpdateSettingsRequestBody"
        },
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UpdateSettingsResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      },
      "delete": {
        "tags": [
          "user"
        ],
        "summary": "Resets settings for the logged in user to default.",
        "description": "Resets any existing settings, reverting the user to default settings.",
        "operationId": "resetSettings",
        "responses": {
          "200": {
            "description": "Success response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ResetSettingsResponse"
                }
              }
            }
          },
          "500": {
            "description": "Database error"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "GameCreate": {
        "type": "object",
        "required": [
          "game_name",
          "vs_team",
          "start_time",
          "game_status"
        ],
        "properties": {
          "game_name": {
            "type": "string",
            "example": "Test Game"
          },
          "vs_team": {
            "type": "string",
            "example": "VS Team Name"
          },
          "start_time": {
            "type": "string",
            "format": "date-time",
            "description": "ISO string representation of game start time",
            "example": "2026-06-01T14:30:00Z"
          },
          "game_status": {
            "type": "string",
            "description": "Status of current game",
            "default": "scheduled",
            "enum": [
              "scheduled",
              "in-progress",
              "completed",
              "cancelled"
            ],
            "example": "scheduled"
          }
        }
      },
      "GameFull": {
        "allOf": [
          {
            "type": "object",
            "required": [
              "game_id"
            ],
            "properties": {
              "game_id": {
                "type": "integer",
                "description": "Auto-incremented unique ID for the game",
                "example": 1
              }
            }
          },
          {
            "$ref": "#/components/schemas/GameCreate"
          }
        ]
      },
      "EventCreate": {
        "type": "object",
        "required": [
          "game_id",
          "event_code",
          "zone_id",
          "team_id",
          "game_clock",
          "game_half"
        ],
        "properties": {
          "game_id": {
            "type": "integer",
            "description": "Associated game_id",
            "example": 1
          },
          "event_code": {
            "type": "string",
            "enum": [
              "A",
              "C",
              "E",
              "K",
              "L",
              "M",
              "P",
              "R",
              "S",
              "T",
              "V",
              "Y"
            ],
            "example": "P"
          },
          "zone_id": {
            "type": "string",
            "enum": [
              "A",
              "B",
              "M",
              "C",
              "D"
            ],
            "example": "M"
          },
          "team_id": {
            "type": "integer",
            "description": "Team 1 - Reds, Team 2 - VS team",
            "enum": [
              1,
              2
            ],
            "example": 1
          },
          "game_clock": {
            "type": "integer",
            "description": "Match time (in seconds)",
            "minimum": 0,
            "example": 20
          },
          "game_half": {
            "type": "integer",
            "enum": [
              1,
              2
            ],
            "example": 1
          }
        }
      },
      "EventFull": {
        "allOf": [
          {
            "type": "object",
            "required": [
              "event_id"
            ],
            "properties": {
              "event_id": {
                "type": "integer",
                "description": "Auto-incremented unique ID for the event",
                "example": 1
              }
            }
          },
          {
            "$ref": "#/components/schemas/EventCreate"
          }
        ]
      },
      "GameCreateResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "game_id"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Game created successfully"
          },
          "game_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "GameUpdateResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "game_id"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Game updated successfully"
          },
          "game_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "GameDeleteResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "game_id"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Game deleted successfully"
          },
          "game_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "EventCreateResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "event_id"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Event logged successfully"
          },
          "event_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "EventUpdateResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "event_id"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Event updated successfully"
          },
          "event_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "EventDeleteResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "event_id"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Event deleted successfully"
          },
          "event_id": {
            "type": "integer",
            "example": 1
          }
        }
      },
      "GetAllGamesResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "games"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "games": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/GameFull"
            },
            "example": [
              {
                "game_id": 1,
                "game_name": "Season 2026 - Week 12",
                "vs_team": "Waratahs",
                "start_time": "2026-05-25T14:30:00.000Z",
                "game_status": "completed"
              },
              {
                "game_id": 2,
                "game_name": "Practice Game vs Storm",
                "vs_team": "Storm",
                "start_time": "2026-06-01T18:00:00.000Z",
                "game_status": "scheduled"
              }
            ]
          }
        }
      },
      "GetSingleGameResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "game"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "game": {
            "$ref": "#/components/schemas/GameFull"
          }
        }
      },
      "MissingGameErrorResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Game not found"
          }
        }
      },
      "NoGamesErrorResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "No games found"
          }
        }
      },
      "GetEventResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "event"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "event": {
            "$ref": "#/components/schemas/EventFull"
          }
        }
      },
      "MissingEventErrorResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "Event not found"
          }
        }
      },
      "NoEventsErrorResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": true
          },
          "message": {
            "type": "string",
            "example": "No Events found"
          }
        }
      },
      "GetGameEventsResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "events"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Success"
          },
          "events": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/EventFull"
            },
            "example": [
              {
                "event_id": 1,
                "game_id": 1,
                "event_code": "P",
                "zone_id": "M",
                "team_id": 1,
                "game_clock": 10,
                "game_half": 1
              },
              {
                "event_id": 2,
                "game_id": 1,
                "event_code": "C",
                "zone_id": "B",
                "team_id": 1,
                "game_clock": 70,
                "game_half": 1
              },
              {
                "event_id": 3,
                "game_id": 1,
                "event_code": "K",
                "zone_id": "A",
                "team_id": 1,
                "game_clock": 130,
                "game_half": 1
              },
              {
                "event_id": 4,
                "game_id": 1,
                "event_code": "T",
                "zone_id": "A",
                "team_id": 1,
                "game_clock": 610,
                "game_half": 1
              }
            ]
          }
        }
      },
      "UserRole": {
        "type": "object",
        "required": [
          "username",
          "role"
        ],
        "properties": {
          "username": {
            "type": "string",
            "description": "Username of the account",
            "example": "admin"
          },
          "role": {
            "type": "string",
            "description": "User access role",
            "enum": [
              "admin",
              "editor",
              "viewer"
            ],
            "example": "admin"
          }
        }
      },
      "UserLogin": {
        "type": "object",
        "required": [
          "username",
          "password"
        ],
        "properties": {
          "username": {
            "type": "string",
            "description": "Username to authenticate",
            "example": "admin"
          },
          "password": {
            "type": "string",
            "description": "Password to authenticate",
            "example": "admin"
          }
        }
      },
      "UserFull": {
        "allOf": [
          {
            "$ref": "#/components/schemas/UserLogin"
          },
          {
            "$ref": "#/components/schemas/UserRole"
          }
        ],
        "example": {
          "username": "test",
          "password": "test",
          "role": "viewer"
        }
      },
      "JWTPayload": {
        "allOf": [
          {
            "$ref": "#/components/schemas/UserRole"
          },
          {
            "type": "object",
            "required": [
              "iat",
              "exp"
            ],
            "properties": {
              "iat": {
                "type": "integer",
                "description": "Issued at timestamp",
                "example": 1787390825
              },
              "exp": {
                "type": "integer",
                "description": "Expiration timestamp",
                "example": 1787477225
              }
            }
          }
        ]
      },
      "UserLoginResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "token_type",
          "token",
          "token_payload"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Login successful"
          },
          "token_type": {
            "type": "string",
            "example": "Bearer"
          },
          "token": {
            "type": "string",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzg3MzkwODI1LCJleHAiOjE3ODc0NzcyMjV9.BKKd_DX2a2DknyHBQq8lZxCcHwD5o3TfDLst0zHY6hg"
          },
          "token_payload": {
            "$ref": "#/components/schemas/JWTPayload"
          }
        }
      },
      "UserCreateResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "User 'test' created successfully with role 'viewer'."
          }
        }
      },
      "GetUsersResponse": {
        "type": "object",
        "required": [
          "error",
          "users"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "users": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/UserRole"
            }
          }
        },
        "example": {
          "error": false,
          "users": [
            {
              "username": "admin",
              "role": "admin"
            },
            {
              "username": "test",
              "role": "viewer"
            }
          ]
        }
      },
      "UserUpdate": {
        "type": "object",
        "required": [
          "username"
        ],
        "properties": {
          "username": {
            "type": "string",
            "example": "test"
          }
        },
        "oneOf": [
          {
            "title": "Update Password Only",
            "type": "object",
            "required": [
              "password"
            ],
            "properties": {
              "password": {
                "type": "string",
                "example": "newpassword"
              }
            }
          },
          {
            "title": "Update Role Only",
            "type": "object",
            "required": [
              "role"
            ],
            "properties": {
              "role": {
                "type": "string",
                "enum": [
                  "admin",
                  "editor",
                  "viewer"
                ],
                "example": "editor"
              }
            }
          },
          {
            "title": "Update Password & Role",
            "type": "object",
            "required": [
              "password",
              "role"
            ],
            "properties": {
              "password": {
                "type": "string",
                "example": "newpassword"
              },
              "role": {
                "type": "string",
                "enum": [
                  "admin",
                  "editor",
                  "viewer"
                ],
                "example": "editor"
              }
            }
          }
        ]
      },
      "UserUpdateResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "User 'test' updated successfully."
          }
        }
      },
      "UserDelete": {
        "type": "object",
        "required": [
          "username"
        ],
        "properties": {
          "username": {
            "$ref": "#/components/schemas/UserRole/properties/username"
          }
        },
        "example": {
          "username": "test"
        }
      },
      "UserDeleteResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "User 'test' deleted successfully."
          }
        }
      },
      "UpdatePassword": {
        "type": "object",
        "required": [
          "current_password",
          "new_password"
        ],
        "properties": {
          "current_password": {
            "type": "string",
            "example": "test"
          },
          "new_password": {
            "type": "string",
            "example": "newpassword"
          }
        }
      },
      "UpdatePasswordResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Password updated successfully."
          }
        }
      },
      "Keybinds": {
        "type": "object",
        "description": "Mapping of game events and controls to QWERTY keyboard keys",
        "required": [
          "Pass",
          "Kick",
          "Catch",
          "Ruck",
          "Scrum",
          "Penalty",
          "Advantage",
          "Turnover",
          "Lineout",
          "Maul",
          "Pause",
          "Add_Time",
          "Remove_Time",
          "Move_Zone_Left",
          "Move_Zone_Right",
          "Swap_Team",
          "Swap_Direction"
        ],
        "properties": {
          "Pass": {
            "type": "string",
            "example": "P"
          },
          "Kick": {
            "type": "string",
            "example": "K"
          },
          "Catch": {
            "type": "string",
            "example": "C"
          },
          "Ruck": {
            "type": "string",
            "example": "R"
          },
          "Scrum": {
            "type": "string",
            "example": "S"
          },
          "Penalty": {
            "type": "string",
            "example": "E"
          },
          "Advantage": {
            "type": "string",
            "example": "A"
          },
          "Turnover": {
            "type": "string",
            "example": "T"
          },
          "Lineout": {
            "type": "string",
            "example": "L"
          },
          "Maul": {
            "type": "string",
            "example": "M"
          },
          "Pause": {
            "type": "string",
            "example": "Space"
          },
          "Add_Time": {
            "type": "string",
            "example": "="
          },
          "Remove_Time": {
            "type": "string",
            "example": "-"
          },
          "Move_Zone_Left": {
            "type": "string",
            "example": "Left Arrow"
          },
          "Move_Zone_Right": {
            "type": "string",
            "example": "Right Arrow"
          },
          "Swap_Team": {
            "type": "string",
            "example": "Tab"
          },
          "Swap_Direction": {
            "type": "string",
            "example": "Up Arrow"
          }
        },
        "example": {
          "Pass": "P",
          "Kick": "K",
          "Catch": "C",
          "Ruck": "R",
          "Scrum": "S",
          "Penalty": "E",
          "Advantage": "A",
          "Turnover": "T",
          "Lineout": "L",
          "Maul": "M",
          "Pause": "Space",
          "Add_Time": "=",
          "Remove_Time": "-",
          "Move_Zone_Left": "Left Arrow",
          "Move_Zone_Right": "Right Arrow",
          "Swap_Team": "Tab",
          "Swap_Direction": "Up Arrow"
        }
      },
      "GetKeybindsResponse": {
        "type": "object",
        "required": [
          "error",
          "keybinds"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "keybinds": {
            "nullable": true,
            "allOf": [
              {
                "$ref": "#/components/schemas/Keybinds"
              }
            ]
          }
        }
      },
      "UpdateKeybindsResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "keybinds"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Keybinds updated successfully."
          },
          "keybinds": {
            "$ref": "#/components/schemas/Keybinds"
          }
        }
      },
      "ResetKeybindsResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Keybinds successfully reset to default."
          }
        }
      },
      "Settings": {
        "type": "object",
        "description": "Modified user settings",
        "required": [
          "Event_History_Length",
          "Outline_Colour",
          "Enable_Keybinds",
          "Large_Buttons",
          "Dark_Mode",
          "Default_Home_Team"
        ],
        "properties": {
          "Event_History_Length": {
            "type": "integer",
            "example": 8
          },
          "Outline_Colour": {
            "type": "string",
            "example": "Green"
          },
          "Enable_Keybinds": {
            "type": "boolean",
            "example": true
          },
          "Large_Buttons": {
            "type": "boolean",
            "example": false
          },
          "Dark_Mode": {
            "type": "boolean",
            "example": false
          },
          "Default_Home_Team": {
            "type": "boolean",
            "example": true
          }
        },
        "example": {
          "Event_History_Length": 8,
          "Outline_Colour": "Green",
          "Enable_Keybinds": true,
          "Large_Buttons": false,
          "Dark_Mode": false,
          "Default_Home_Team": true
        }
      },
      "GetSettingsResponse": {
        "type": "object",
        "required": [
          "error",
          "settings"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "settings": {
            "nullable": true,
            "allOf": [
              {
                "$ref": "#/components/schemas/Settings"
              }
            ]
          }
        }
      },
      "UpdateSettingsResponse": {
        "type": "object",
        "required": [
          "error",
          "message",
          "settings"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Settings updated successfully."
          },
          "settings": {
            "$ref": "#/components/schemas/Settings"
          }
        }
      },
      "ResetSettingsResponse": {
        "type": "object",
        "required": [
          "error",
          "message"
        ],
        "properties": {
          "error": {
            "type": "boolean",
            "example": false
          },
          "message": {
            "type": "string",
            "example": "Settings successfully reset to default."
          }
        }
      }
    },
    "requestBodies": {
      "GameInputRequestBody": {
        "description": "Payload required to create/update a game record",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/GameCreate"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/GameCreate"
            }
          }
        }
      },
      "EventInputRequestBody": {
        "description": "Payload required to create/update a game event",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/EventCreate"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/EventCreate"
            }
          }
        }
      },
      "UserLoginRequestBody": {
        "description": "Payload required to authenticate a user",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserLogin"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/UserLogin"
            }
          }
        }
      },
      "UserCreateRequestBody": {
        "description": "Payload required to create a new user",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserFull"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/UserFull"
            }
          }
        }
      },
      "UserUpdateRequestBody": {
        "description": "Payload required to update a user's password or role. Must supply username and at least password or role.",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserUpdate"
            },
            "examples": {
              "updateRoleOnly": {
                "summary": "Option 1: Update Role Only",
                "description": "Updates only the user's role",
                "value": {
                  "username": "test",
                  "role": "editor"
                }
              },
              "updatePasswordOnly": {
                "summary": "Option 2: Update Password Only",
                "description": "Updates only the user's password",
                "value": {
                  "username": "test",
                  "password": "newpassword"
                }
              },
              "updateBoth": {
                "summary": "Option 3: Update Password and Role",
                "description": "Updates both the password and role simultaneously",
                "value": {
                  "username": "test",
                  "password": "newpassword",
                  "role": "editor"
                }
              }
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/UserUpdate"
            },
            "examples": {
              "updatePasswordOnly": {
                "summary": "Option 1: Update Password Only",
                "value": {
                  "username": "test",
                  "password": "newSecurePassword123"
                }
              },
              "updateRoleOnly": {
                "summary": "Option 2: Update Role Only",
                "value": {
                  "username": "test",
                  "role": "editor"
                }
              },
              "updateBoth": {
                "summary": "Option 3: Update Password and Role",
                "value": {
                  "username": "test",
                  "password": "newSecurePassword123",
                  "role": "editor"
                }
              }
            }
          }
        }
      },
      "UserDeleteRequestBody": {
        "description": "Payload required to delete a user account",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserDelete"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/UserDelete"
            }
          }
        }
      },
      "UpdatePasswordRequestBody": {
        "description": "Payload required to update the password of a logged in user",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UpdatePassword"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/UpdatePassword"
            }
          }
        }
      },
      "UpdateKeybindsRequestBody": {
        "description": "Payload required to update user keybindings",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Keybinds"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/Keybinds"
            }
          }
        }
      },
      "UpdateSettingsRequestBody": {
        "description": "Payload required to update user settings",
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/Settings"
            }
          },
          "application/x-www-form-urlencoded": {
            "schema": {
              "$ref": "#/components/schemas/Settings"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "Enter your JWT token directly (e.g. eyJhbGciOiJKV1Qi...)"
      }
    }
  }
}